### PR TITLE
2017.1: bump version number

### PR DESCRIPTION
**Pull request by rc**
New release of SfePy.

### CODE REVIEW

**Comment by rc** [comment]
@wd15, the travis-ci job failed IMHO due to the S3 outage in AWS - is there a way to re-run it?

**Comment by wd15** [comment]
@rc, there is a "restart build" button way over to the right of the page and near the top on the Travis build page for build [206123487](https://travis-ci.org/conda-forge/sfepy-feedstock/builds/206123487).

**Comment by rc** [comment]
@wd15, I do see (and use) that button on my repos, but not on this one - maybe I do not have the right permissions? Can you restart it? Thanks.

**Comment by wd15** [comment]
@rc, I think you need to be added as an admin to this repo. I don't have permission, but perhaps one of the Condaforge people could do that.

**Comment by rc** [comment]
Thanks, @wd15, for re-running it. All checks passed, we are ready to merge. Will you do it?

**Comment by rc** [comment]
As for the rights, I have just joined the conda-forge organization - maybe that will help. Edit: yes, it did help.

**Comment by rc** [comment]
Thanks!

**Pull request merged**
