### PR TITLE
2019.1

### PR DESCRIPTION
**Pull request by rc**
@BubuLK, maybe we merge this as is, and then deal with #13 ?

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by BubuLK** [comment]
Yes, of course. Sorry for the mess...

**Comment by rc** [comment]
@BubuLK are the linux/windows failures serious? I mean, shall we merge this, or not yet? :)

**Comment by BubuLK** [comment]
Not surre, but still work in progress. I would prefere  to wait with merge...

**Comment by rc** [comment]
@BubuLK https://github.com/sfepy/sfepy/pull/504 is in, shall I tag a new release (2019.1.1) and update this PR?

**Pull request merged**
