### PR TITLE
new build system test

### PR DESCRIPTION
**Pull request by rc**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yosefm** [comment]
Some progress: under mambabuild, CMake does not choose the right generator (Ninja) but uses the plain MSVC generator. I don't know why Ninja works and the other doesn't (seems like a mix in target and host architecture, one being win32 and the other amd64).

The missed generator choice appears to be unique to azure images:
https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-windows-cmake

The package is built successfully if I add `["-G", "Ninja"]` to the cmake args in setup.py. I'm not sure yet that this is the best way to handle the choice, and have not tested on platforms other than Windows. Still, that shows the way forward.

**Comment by yosefm** [comment]
Update: tested further and the addition seems harmless on other platforms. so I updated the sfepy PR with that change. It should now, fingers crossed, pass on all platforms with mamba.

**Comment by rc** [comment]
Thanks! It did fix the windows, but broke the posix platforms. Maybe ninja needs to be installed explicitly?

**Comment by yosefm** [comment]
Halleluja!!

**Comment by rc** [comment]
I do not think the failures are caused by the manifest fixing commits, and before those it worked. Something probably changed on the conda-forge testing machinery side. So let us ignore this for the moment. I will merge the build system to sfepy and return to this later when preparing the next release.

**Comment by rc** [comment]
The changes were included in #52, closing.

**Pull request closed without merging**
