### PR TITLE
2018.2

### PR DESCRIPTION
**Pull request by rc**
2018.2 release.

### CODE REVIEW

**Comment by rc** [comment]
@wd15 Ping :)

**Comment by wd15** [comment]
@rc, all looks good, I'll merge it.

I've had an [issue](https://github.com/materialsinnovation/pymks/issues/346) with Sfepy. I think the Sfepy API has changed so I've pinned the PyMKS dependency to 2017.4.1. Just letting you know that API changes do have impacts, but that's fine. I'll get around to updating it soon.

Also, I have an [Nix recipe for Sfepy](https://github.com/materialsinnovation/pymks/blob/develop/nix/sfepy.nix). I could do a more complete version for Sfepy and do a pull request for it if you're interested. Something like [this](https://github.com/materialsinnovation/pymks/blob/develop/default.nix) that goes with the source code. Let me know if that interests you. I much prefer it to using Conda now.

**Comment by rc** [comment]
Thanks!

BTW. the problem you found is likely related to [this](https://mail.python.org/mm3/archives/list/sfepy@python.org/thread/2NAW34QRZTY2LX4SMTZEZMGNBBHCZTYQ/). There was no feedback to the e-mail for some time, so I went on and merged it.

Let me know if you need help fixing your issue - do you have a simple example, where it manifests? I might give it a shot and fix it myself.

I do not know nix, but it seems useful from a quick glance. How does it compare to package managers like spack? BTW. last year I made a [package](http://spack.readthedocs.io/en/latest/package_list.html#py-sfepy) for spack.

**Comment by wd15** [comment]
@rc, see below.

On Fri, Jun 22, 2018 at 2:51 PM, Robert Cimrman
<notifications@github.com> wrote:
>
> Let me know if you need help fixing your issue - do you have a simple example, where it manifests? I might give it a shot and fix it myself.

Yes, the problem happens when I run [this
example](https://github.com/materialsinnovation/pymks/blob/master/pymks/datasets/elastic_FE_simulation.py).

> I do not know nix, but it seems useful from a quick glance. How does it compare to package managers like spack? BTW. last year I made a package for spack.

I hadn't heard of Spack. Nix is an actual OS as well as a package
manager. Anyway, some discussion that I found

 - https://news.ycombinator.com/item?id=11088125
 - https://www.reddit.com/r/linux/comments/4ohvur/nix_vs_snap_vs_flatpak_what_are_the_differences/

I would say that Nix is elegant and reliable and also completely
functional (i.e. uses its own functional programming language).

--
Daniel Wheeler

**Pull request merged**
