### PR TITLE
2018.1

### PR DESCRIPTION
**Pull request by rc**
2018.1 release.

### CODE REVIEW

**Comment by wd15** [comment]
@rc, do you want to try and restart the build that hasn't finished?

**Comment by rc** [comment]
It looks like all checks passed - did you restart it?

**Comment by wd15** [comment]
@rc, no I didn't restart it. The tests still hadn't finished after 10 hours so I thought something had stalled, but they must have finished after I posted my comment. I'll merge this now.

**Comment by rc** [comment]
@wd15, I see, thanks!

**Pull request merged**
