### PR TITLE
2018.3

### PR DESCRIPTION
**Pull request by rc**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rc** [comment]
Hi @wd15, I wanted to bump the version number for the latest sfepy release (hopefully it will not break anything), but for some reason,  AppVeyor fails to install pytables properly.  I am not sure how to debug this, so any help would be appreciated!

**Comment by wd15** [comment]
@rc, I'm not sure what's going on. Maybe we should ping someone from Conda-forge to see. I'm not sure how to debug without modifying Sfepy. Also, what happens if you ask for an older version of pytables, maybe 2.x?

**Comment by rc** [comment]
I have just tried <=3.2 and got unsatisfiable dependency errors. But maybe I used a wrong wrong specification.

**Comment by rc** [comment]
Thanks @BubuLK, the tests pass, so I will merge this PR.

**Pull request merged**
