### PR TITLE
2023.1

### PR DESCRIPTION
**Pull request by rc**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rc** [comment]
Checking the new build system proposed by https://github.com/sfepy/sfepy/pull/960

**Comment by yosefm** [comment]
Cmake can't find a c++ compiler, but why should that happen when a C compiler is found? I see that conda sets up the compilers, but I don't have experience with building conda packages. I'll try to find time to try it later in the week.

**Comment by yosefm** [comment]
Please try with the latest version of the branch. I specified for CMake to only enable the C language (the default includes C++). Another way to handle this is to specify a c++ compiler in the conda recipe, but if the CMake route works, I think it's probably better.

**Comment by rc** [comment]
Thanks, trying...

**Comment by rc** [comment]
It fails with:
```
2023-03-18T12:54:33.4409412Z   -- The CXX compiler identification is unknown
2023-03-18T12:54:33.4444513Z   CMake Error at CMakeLists.txt:4 (ENABLE_LANGUAGE):
2023-03-18T12:54:33.4453763Z     No CMAKE_CXX_COMPILER could be found.
2023-03-18T12:54:33.4463089Z 
2023-03-18T12:54:33.4474162Z     Tell CMake where to find the compiler by setting either the environment
2023-03-18T12:54:33.4483725Z     variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
2023-03-18T12:54:33.4493533Z     to the compiler, or to the compiler name if it is in the PATH.
```

**Comment by yosefm** [comment]
Another commit to the sfepy branch: added the languages parameter in setup() call. This seems to work locally, as in CMake now doesn't look for a CXX compiler. I'm sorry that I can't test the full conda flow yet as I have no docker setup, but I think that fix could be the last.

**Comment by rc** [comment]
Progress! Now only windows builds fail due to some linking error.

**Comment by yosefm** [comment]
I don't have an easy access to a Windows machine. I'll try to set something up at work, but that may take some time. It's strange that the Windows build passes normally but not with conda.

**Comment by yosefm** [comment]
Update: managed to run the mamba build on a Windows machine and reproduce the problem. Adding VERBOSE=1 to the environment, I can see what symbols are missing. It looks like mamba's cmake can't find object files in the same build tree due to different settings. I'm not sure what yet. Outputs are places under _skbuild/.../cmake_build/<module_path>/Release instead of directly under _skbuild/.../cmake_build/<module_path>, though this could be just one symptom. Don't know where it's coming from yet.

**Comment by rc** [comment]
OK, thanks for investigating this.

I would like to make the 2023.1 release next week, but there is no need to hurry this - I will merge the new build system PR after the release to try it out myself and have enough time for that.

**Comment by rc** [comment]
I will merge this and open a new PR to test the new build system.

**Pull request merged**
