### PR TITLE
Do not skip Python 3.6

### PR DESCRIPTION
**Pull request by rc**

### CODE REVIEW

**Comment by rc** [comment]
Hi @wd15, I would like to re-enable python 3.6 - it seems to work. Do you recall why we disabled that? There were some python 3.6 related fixes in sfepy in the meantime, so the skipping is IMHO no longer needed.

**Comment by rc** [comment]
The tests seem to pass, shall we merge it? Should I increase the build number?

**Comment by wd15** [comment]
@rc, I think it was disabled because of dependency issues, but try again anyway.

Regarding the build number, yes, I think that if the build changes for the same package version then you need to bump the build number. The docs say that the build number needs to be reset to 0 when the version number is updated.

**Comment by rc** [comment]
@wd15 OK, I have bumped the build number. The current anaconda now ships with Python 3.6, so IMHO the dependency issues will be no more present. We will see - I will merge this once the tests finish.

**Pull request merged**
